#!/usr/bin/env bash
# Build a native Arch Linux package (sinkd-*.pkg.tar.zst) with static musl binary into artifacts/.
# Requires: base-devel, bump, cargo, rustup, musl toolchain for the target (see Arch wiki / musl).
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd -- "$SCRIPT_DIR/../.." && pwd)
cd "$ROOT"

if ! command -v bump >/dev/null 2>&1; then
  echo "bump not found. Install bump (https://github.com/launchfirestorm/bump) and ensure it is on PATH." >&2
  exit 1
fi

if ! command -v makepkg >/dev/null 2>&1; then
  echo "makepkg not found. Install base-devel (pacman -S base-devel) on Arch." >&2
  exit 1
fi

VERSION=$(bump -b)

case "$(uname -m)" in
x86_64)
  MUSL_TARGET=x86_64-unknown-linux-musl
  ;;
aarch64)
  MUSL_TARGET=aarch64-unknown-linux-musl
  ;;
*)
  echo "Unsupported machine: $(uname -m)" >&2
  exit 1
  ;;
esac

OUT="${ROOT}/artifacts"
mkdir -p "${OUT}"

WORKDIR=$(mktemp -d)
cleanup() { rm -rf "${WORKDIR}"; }
trap cleanup EXIT

# Embed paths and musl triple; makepkg runs build/package against this checkout.
cat >"${WORKDIR}/PKGBUILD" <<EOF
# Generated by pkg/arch/create.sh — version from \`bump -b\` / bump.toml
pkgname=sinkd
pkgver=${VERSION}
pkgrel=1
pkgdesc="Local sync daemon wrapping rsync (sinkd), static musl binary"
arch=('x86_64' 'aarch64')
url="https://github.com/ballast-dev/sinkd"
license=('MIT')
depends=('rsync')
# No makedepends for pacman rust/cargo — build uses rustup (~/.cargo/bin). Declaring cargo/rust here
# forces makepkg -s to sudo pacman, which breaks non-interactive CI. Install rustup + musl target before
# running this script; ensure rsync is installed (depends) or use makepkg -s with passwordless sudo.
makedepends=()
options=('!lto' '!debug')

build() {
  cd "$ROOT"
  export PATH="\$HOME/.cargo/bin:\$PATH"
  if command -v rustup >/dev/null 2>&1; then
    rustup target add ${MUSL_TARGET} 2>/dev/null || true
  fi
  cargo build -p sinkd --release --locked --target ${MUSL_TARGET}
}

package() {
  _bin="\${CARGO_TARGET_DIR:-$ROOT/target}/${MUSL_TARGET}/release/sinkd"
  install -Dm755 "\${_bin}" "\${pkgdir}/usr/bin/sinkd"
  install -Dm644 "$ROOT/cfg/system/sinkd.conf" "\${pkgdir}/etc/sinkd.conf"
  install -Dm644 "$ROOT/cfg/user/sinkd.conf" "\${pkgdir}/usr/share/sinkd/sinkd.user.conf"
  # install -Dm644 "$ROOT/cfg/user/sinkd.conf" "\${pkgdir}/etc/skel/.config/sinkd/sinkd.conf"
  if [[ -f "$ROOT/LICENSE" ]]; then
    install -Dm644 "$ROOT/LICENSE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
  fi
}
EOF

(
  cd "${WORKDIR}"
  makepkg -fs --cleanbuild --noconfirm
)

shopt -s nullglob
for f in "${WORKDIR}"/*.pkg.tar.zst; do
  mv -f "${f}" "${OUT}/"
  echo "Wrote ${OUT}/$(basename "${f}")"
done
