use clap::{Arg, ArgAction, Command};

#[rustfmt::skip]
pub fn build_sinkd() -> Command {
    Command::new("sinkd")
        .about("deployable cloud")
        .version(env!("CARGO_PKG_VERSION"))
        .subcommand(Command::new("add")
            .about("Adds PATH to watch list")
            .arg(Arg::new("share")
                .short('s')
                .long("share")
                .value_name("SHARE")
                .num_args(1)
                .action(ArgAction::Append)
                .help("add watch for multiple users")
            )
            .arg(Arg::new("path")
                .value_name("PATH")
                .num_args(0..)
                .help("sinkd starts watching path")
            )
        )
        .subcommand(Command::new("ls")
            .alias("list")
            .about("List currently watched files from given PATH")
            .arg(Arg::new("path")
                .value_name("PATH")
                // need to revisit, should user have explicit control
                // possible -r flag for recursive 
                .required(false)
                .num_args(0..)
                .help("list watched files and directories")
            )
        )
        .subcommand(Command::new("rm")
            .alias("remove")
            .about("Removes PATH from watch list")
            .arg(Arg::new("path")
                .value_name("PATH")
                .required(true)
                .num_args(1..)
            )
        )
        //* sinkd server start|stop|restart
        //* sinkd client start|stop|restart
        .subcommand(Command::new("server")
            .about("manage sinkd server")
            // .subcommand(Command::new("start")
            //     .
            // )
        )
        .subcommand(Command::new("start")
            .about("Starts the daemon")
            // .override_usage("sinkd start [--client | --server]")
            .arg(Arg::new("client")
                .value_name("CLIENT")
                .short('c')
                .long("client")
                .action(ArgAction::SetTrue)
                .conflicts_with("server")
                .help("start sinkd in client mode")
            )
            .arg(Arg::new("server")
                .value_name("SERVER")
                .short('s')
                .long("server")
                .conflicts_with("client")
                .action(ArgAction::SetTrue)
                .help("start sinkd in server mode")
            )
        )
        .subcommand(Command::new("stop")
            .about("Stops daemon")
        )
        .subcommand(Command::new("restart")
            .about("Restarts sinkd, reloading configuration")
        )
        .subcommand(Command::new("log")
            .about("test out logging")
        )
        .arg(Arg::new("verbose")
            .short('v')
            .action(ArgAction::Count)
            .help("verbosity, corresponds to log level, default='vv'=warn\nv=error,vv=warn,vvv=info,vvvv=debug")
            .global(true)
        )
        .arg(Arg::new("debug")
            .short('d')
            .long("debug")
            .action(ArgAction::SetTrue)
            .help("log files to /tmp, log-level set to debug")
            .global(true)
        )
        .arg(Arg::new("system-config")
            .long("sys-cfg")
            .num_args(1)
            .default_value("/etc/sinkd.conf")
            .help("system configuration file to use")
            .global(true)
        )
        .arg(Arg::new("user-configs")
            .long("usr-cfg")
            .num_args(1..)
            .action(ArgAction::Append)
            //? long help is '--help' versus '-h'
            .long_help("providing this flag will override supplied users in system config")
            .help("user configuration files to use\ndefault: ~/.config/sinkd.conf")
            .global(true)
        )
}
